---
deployment:
  tasks:
    - export DEPLOYPATH=/home/swatini/public_html/
    - cp -r $DEPLOYPATH/dist/* $DEPLOYPATH/     # Copy built files to the root of your deployment path
    - rm -rf $DEPLOYPATH/dist                  # Remove the 'dist' folder (optional)
  hooks:
    after:deploy:
      - echo "React Vite app deployed successfully!"
